---
timelines:
  - {'date': '2016-09-12T00:00', 'name': 'PTL nomination starts'}
  - {'date': '2016-09-18T23:45', 'name': 'PTL nomination ends'}
  - {'date': '2016-09-19T00:00', 'name': 'PTL elections begins'}
  - {'date': '2016-09-25T23:45', 'name': 'PTL elections ends'}
  - {'date': '2016-09-26T00:00', 'name': 'TC nomination starts'}
  - {'date': '2016-10-01T23:45', 'name': 'TC nomination ends'}
  - {'date': '2016-10-03T00:00', 'name': 'TC elections begins'}
  - {'date': '2016-10-09T23:45', 'name': 'TC elections ends'}
